# _config.yml (Final Corrected Version)

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Willis Wong"
description: "Personal academic website of Willis Wong"
baseurl: "" # the subpath of your site, e.g. /blog. For user pages, this is often blank.
url: "https://wclisfy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Remote Theme
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache

# Minimal Mistakes Theme Settings
minimal_mistakes_skin: "contrast"

# Author Information
author:
  name   : "Willis Wong"
  bio    : "A linguist working on morphology and its interfaces."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wclisfy@gmail.com"

# Defaults for Posts and Pages
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true