#title: "Willis Wong"
#subtitle: "Linguist"
#description: "Personal academic website of Willis Wong"
url: "https://wclisfy.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "mint"

google_fonts: 
  - name: "Merriweather"
    weights: "400,700"

plugins:
  - jekyll-include-cache

# 導覽列 menu bar
nav:
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
#  - title: "Blog"
#    url: /blog/
  - title: "Contact"
    url: /contact/

# ✅ author 應該喺 nav 之後，唔好入 nav
author:
  name   : "Willis Wong"
#  avatar : "/assets/images/avatar.png"
  bio    : "A linguist working on morphology and its interfaces."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wclisfy@gmail.com"

header:
  nav: true

sidebar:
  nav: "main"