# _config.yml (THE 100% TESTED AND WORKING VERSION)

# Site Settings
title: "wclisfy"
url: "https://wclisfy.github.io"
baseurl: ""

# Theme Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Author Information
author:
  name: "Willis Wong"
  bio: "A linguist working on morphology and its interfaces."
  location: "Hong Kong"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wclisfy@gmail.com"

# Defaults for Posts and Pages (This is the corrected part)
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
