# _config.yml (FINAL CORRECTED VERSION WITH PROPER INDENTATION)

# Site Settings
title: "Willis Wong"
url: "https://wclisfy.github.io"
baseurl: ""

# Theme Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Author Information
author:
  name: "Willis Wong"
  bio: "A linguist working on morphology and its interfaces."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wclisfy@gmail.com"

# Defaults for Posts and Pages
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "single"
      author_profile: true