title: "Willis Wong"
subtitle: "Linguist"
description: "Personal academic website of Willis Wong"
url: "https://wclisfy.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mint"

google_fonts:
  - name: "Merriweather"
    weights: "400,700"

author:
  name: "Willis Wong"
  avatar: "/assets/images/avatar.png"
  bio: "Linguist working on morphosyntax and sound symbolism."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:willis@something.com"
    - label: "BlueSky"
      icon: "fab fa-bluesky"
      url: "https://bsky.app/profile/yourname.bsky.social"

# Navigation bar
nav:
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/
