# _config.yml (Corrected Version)

url: "https://wclisfy.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"

google_fonts: 
  - name: "Merriweather"
    weights: "400,700"

# 導覽列 menu bar
nav:
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Contact"
    url: /contact/

# 作者簡介
author:
  name   : "Willis Wong"
  bio    : "A linguist working on morphology and its interfaces."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wclisfy@gmail.com"

# 全域預設值
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true