title: "Willis Wong"
subtitle: "Linguist"
description: "Personal academic website of Willis Wong"
url: "https://wclisfy.github.io"

# ✅ 使用 remote theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# ✅ 使用 Mint skin（你可以試下 air/sunrise）
minimal_mistakes_skin: "mint"

plugins:
  - jekyll-include-cache

# ✅ 使用 sidebar layout
layout: sidebar

# ✅ Font 設定
google_fonts:
  - name: "Merriweather"
    weights: "400,700"

# ✅ 左邊 Author profile
author:
  name   : "Willis Wong"
  avatar : "/assets/images/avatar.png"  # 放你張頭像
  bio    : "Linguist working on morphosyntax and sound symbolism."

  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:willis@something.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/wclisfy"
    - label: "BlueSky"
      icon: "fab fa-bluesky"
      url: "https://bsky.app/profile/yourname.bsky.social"

# ✅ 上方 menu（navbar）
nav:
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/
