# Name of your workflow
name: Build and Deploy Jekyll Site to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Sets up Ruby and caches dependencies for speed
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # The version of Ruby you want to use
          bundler-cache: true # Automatically runs 'bundle install' and caches gems

      # 3. Builds the Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build
        # This sets an environment variable to ensure GitHub Pages specific settings are used
        env:
          JEKYLL_ENV: production

      # 4. Deploys the built site to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # This token is provided by GitHub Actions automatically
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The folder that contains your built site
          publish_dir: ./_site